// Code generated by go-swagger; DO NOT EDIT.

// Package restapi hello
//
//  this is prototype app
//  Schemes:
//    http
//  Host: localhost:8000
//  BasePath: /test
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
